// DUT 编译清单：pulp axi 全库（Bender 依赖序，axi_pkg 起、axi_test 止；DUT 本体 axi_xbar.sv）
+incdir+../vendor/axi/include
+incdir+../vendor/common_cells/include
../vendor/axi/src/axi_pkg.sv
../vendor/axi/src/axi_intf.sv
../vendor/axi/src/axi_atop_filter.sv
../vendor/axi/src/axi_burst_splitter_gran.sv
../vendor/axi/src/axi_burst_unwrap.sv
../vendor/axi/src/axi_bus_compare.sv
../vendor/axi/src/axi_cdc_dst.sv
../vendor/axi/src/axi_cdc_src.sv
../vendor/axi/src/axi_cut.sv
../vendor/axi/src/axi_delayer.sv
../vendor/axi/src/axi_demux_simple.sv
../vendor/axi/src/axi_dw_downsizer.sv
../vendor/axi/src/axi_dw_upsizer.sv
../vendor/axi/src/axi_fifo.sv
../vendor/axi/src/axi_fifo_delay_dyn.sv
../vendor/axi/src/axi_id_remap.sv
../vendor/axi/src/axi_id_prepend.sv
../vendor/axi/src/axi_inval_filter.sv
../vendor/axi/src/axi_isolate.sv
../vendor/axi/src/axi_join.sv
../vendor/axi/src/axi_lite_demux.sv
../vendor/axi/src/axi_lite_dw_converter.sv
../vendor/axi/src/axi_lite_from_mem.sv
../vendor/axi/src/axi_lite_join.sv
../vendor/axi/src/axi_lite_lfsr.sv
../vendor/axi/src/axi_lite_mailbox.sv
../vendor/axi/src/axi_lite_mux.sv
../vendor/axi/src/axi_lite_regs.sv
../vendor/axi/src/axi_lite_to_apb.sv
../vendor/axi/src/axi_lite_to_axi.sv
../vendor/axi/src/axi_modify_address.sv
../vendor/axi/src/axi_mux.sv
../vendor/axi/src/axi_rw_join.sv
../vendor/axi/src/axi_rw_split.sv
../vendor/axi/src/axi_serializer.sv
../vendor/axi/src/axi_slave_compare.sv
../vendor/axi/src/axi_throttle.sv
../vendor/axi/src/axi_to_detailed_mem.sv
../vendor/axi/src/axi_burst_splitter.sv
../vendor/axi/src/axi_cdc.sv
../vendor/axi/src/axi_demux.sv
../vendor/axi/src/axi_err_slv.sv
../vendor/axi/src/axi_dw_converter.sv
../vendor/axi/src/axi_from_mem.sv
../vendor/axi/src/axi_id_serialize.sv
../vendor/axi/src/axi_lfsr.sv
../vendor/axi/src/axi_multicut.sv
../vendor/axi/src/axi_to_axi_lite.sv
../vendor/axi/src/axi_to_mem.sv
../vendor/axi/src/axi_zero_mem.sv
../vendor/axi/src/axi_interleaved_xbar.sv
../vendor/axi/src/axi_iw_converter.sv
../vendor/axi/src/axi_lite_xbar.sv
../vendor/axi/src/axi_xbar_unmuxed.sv
../vendor/axi/src/axi_to_mem_banked.sv
../vendor/axi/src/axi_to_mem_interleaved.sv
../vendor/axi/src/axi_to_mem_split.sv
../vendor/axi/src/axi_xbar.sv
../vendor/axi/src/axi_xp.sv
../vendor/axi/src/axi_chan_compare.sv
../vendor/axi/src/axi_dumper.sv
../vendor/axi/src/axi_sim_mem.sv
../vendor/axi/src/axi_test.sv
