// vendor 基础库编译清单（依赖序取自各上游 Bender.yml；照搬 floo_axi_chimney 已在 VCS-2018 验证的顺序，剪除 deprecated/test）
../vendor/tech_cells_generic/src/rtl/tc_sram.sv
../vendor/tech_cells_generic/src/rtl/tc_sram_impl.sv
../vendor/tech_cells_generic/src/rtl/tc_clk.sv
../vendor/common_cells/src/binary_to_gray.sv
../vendor/common_cells/src/cb_filter_pkg.sv
../vendor/common_cells/src/cc_onehot.sv
../vendor/common_cells/src/cdc_reset_ctrlr_pkg.sv
../vendor/common_cells/src/cf_math_pkg.sv
../vendor/common_cells/src/clk_int_div.sv
../vendor/common_cells/src/credit_counter.sv
../vendor/common_cells/src/delta_counter.sv
../vendor/common_cells/src/ecc_pkg.sv
../vendor/common_cells/src/edge_propagator_tx.sv
../vendor/common_cells/src/exp_backoff.sv
../vendor/common_cells/src/fifo_v3.sv
../vendor/common_cells/src/gray_to_binary.sv
../vendor/common_cells/src/heaviside.sv
../vendor/common_cells/src/isochronous_4phase_handshake.sv
../vendor/common_cells/src/isochronous_spill_register.sv
../vendor/common_cells/src/lfsr.sv
../vendor/common_cells/src/lfsr_16bit.sv
../vendor/common_cells/src/lfsr_8bit.sv
../vendor/common_cells/src/lossy_valid_to_stream.sv
../vendor/common_cells/src/mv_filter.sv
../vendor/common_cells/src/onehot_to_bin.sv
../vendor/common_cells/src/plru_tree.sv
../vendor/common_cells/src/passthrough_stream_fifo.sv
../vendor/common_cells/src/popcount.sv
../vendor/common_cells/src/ring_buffer.sv
../vendor/common_cells/src/rr_arb_tree.sv
../vendor/common_cells/src/rstgen_bypass.sv
../vendor/common_cells/src/serial_deglitch.sv
../vendor/common_cells/src/shift_reg.sv
../vendor/common_cells/src/shift_reg_gated.sv
../vendor/common_cells/src/spill_register_flushable.sv
../vendor/common_cells/src/stream_demux.sv
../vendor/common_cells/src/stream_filter.sv
../vendor/common_cells/src/stream_fork.sv
../vendor/common_cells/src/stream_intf.sv
../vendor/common_cells/src/stream_join_dynamic.sv
../vendor/common_cells/src/stream_mux.sv
../vendor/common_cells/src/stream_throttle.sv
../vendor/common_cells/src/sub_per_hash.sv
../vendor/common_cells/src/sync.sv
../vendor/common_cells/src/sync_wedge.sv
../vendor/common_cells/src/unread.sv
../vendor/common_cells/src/read.sv
../vendor/common_cells/src/addr_decode_dync.sv
../vendor/common_cells/src/boxcar.sv
../vendor/common_cells/src/cdc_2phase.sv
../vendor/common_cells/src/cdc_4phase.sv
../vendor/common_cells/src/clk_int_div_static.sv
../vendor/common_cells/src/trip_counter.sv
../vendor/common_cells/src/addr_decode.sv
../vendor/common_cells/src/addr_decode_napot.sv
../vendor/common_cells/src/multiaddr_decode.sv
../vendor/common_cells/src/cb_filter.sv
../vendor/common_cells/src/cdc_fifo_2phase.sv
../vendor/common_cells/src/clk_mux_glitch_free.sv
../vendor/common_cells/src/counter.sv
../vendor/common_cells/src/ecc_decode.sv
../vendor/common_cells/src/ecc_encode.sv
../vendor/common_cells/src/edge_detect.sv
../vendor/common_cells/src/lzc.sv
../vendor/common_cells/src/max_counter.sv
../vendor/common_cells/src/rstgen.sv
../vendor/common_cells/src/spill_register.sv
../vendor/common_cells/src/stream_delay.sv
../vendor/common_cells/src/stream_fifo.sv
../vendor/common_cells/src/stream_fork_dynamic.sv
../vendor/common_cells/src/stream_join.sv
../vendor/common_cells/src/cdc_reset_ctrlr.sv
../vendor/common_cells/src/cdc_fifo_gray.sv
../vendor/common_cells/src/fall_through_register.sv
../vendor/common_cells/src/id_queue.sv
../vendor/common_cells/src/stream_to_mem.sv
../vendor/common_cells/src/stream_arbiter_flushable.sv
../vendor/common_cells/src/stream_fifo_optimal_wrap.sv
../vendor/common_cells/src/stream_register.sv
../vendor/common_cells/src/stream_xbar.sv
../vendor/common_cells/src/cdc_fifo_gray_clearable.sv
../vendor/common_cells/src/cdc_2phase_clearable.sv
../vendor/common_cells/src/mem_to_banks_detailed.sv
../vendor/common_cells/src/stream_arbiter.sv
../vendor/common_cells/src/stream_omega_net.sv
../vendor/common_cells/src/mem_to_banks.sv
../vendor/common_cells/src/edge_propagator_ack.sv
../vendor/common_cells/src/edge_propagator.sv
../vendor/common_cells/src/edge_propagator_rx.sv
../vendor/common_verification/src/clk_rst_gen.sv
../vendor/common_verification/src/sim_timeout.sv
../vendor/common_verification/src/stream_watchdog.sv
../vendor/common_verification/src/signal_highlighter.sv
../vendor/common_verification/src/rand_id_queue.sv
../vendor/common_verification/src/rand_stream_mst.sv
../vendor/common_verification/src/rand_synch_holdable_driver.sv
../vendor/common_verification/src/rand_verif_pkg.sv
../vendor/common_verification/src/rand_synch_driver.sv
../vendor/common_verification/src/rand_stream_slv.sv
