// tb/axi_txn.sv — M1 UVM env transaction items. `include-d from tb_pkg.sv
// (package xbar_tb_pkg), after xbar_types_pkg/axi_if are compiled.
//
// axi_seq_item: stimulus generated by a slvport sequence and driven onto a
// crossbar slave port (write or read burst request). AW/AR fields only —
// data/strb for writes are supplied inline.
//
// axi_obs_item: what a monitor observed on the bus (request- or full
// round-trip-side), fed to the scoreboard's analysis imps. One class serves
// both "input observation" (slv side, spec §5.1 source index) and "output
// observation" (mst side) roles per scoreboard_refmodel.md §0; `port_idx`
// carries whichever port the observing monitor is attached to.

class axi_seq_item extends uvm_sequence_item;
  rand bit               is_write;
  rand xbar_types_pkg::addr_t addr;
  rand axi_pkg::len_t     len;   // AxLEN (beats - 1)
  axi_pkg::size_t         size; // fixed full-width beats (BEAT_SIZE)
  axi_pkg::burst_t        burst; // fixed INCR
  rand xbar_types_pkg::id_slv_t id;
  // aw.atop encoding (spec §6.1: an ATOP transaction is an AW with
  // aw.atop != '0; encodings from vendor/axi/src/axi_pkg.sv ATOP_*, the DV
  // parameter-definition source). '0 for every ordinary write; M2-AT01
  // sequences set an ATOP_ATOMICLOAD encoding (read response required,
  // aw.atop[ATOP_R_RESP], spec §6.3).
  axi_pkg::atop_t         atop;
  xbar_types_pkg::data_t  wdata[$];
  xbar_types_pkg::strb_t  wstrb[$];
  // M4-FT01 fall-through probe selector (testplan M4-FT01, spec §2.1):
  // when set on a write item, the driver (slvport_agent.sv drive_write_ft)
  // presents AW and this burst's FIRST W beat concurrently instead of
  // waiting out the AW handshake first — the stimulus shape needed to give
  // FallThrough=1 configurations (cfgE) a chance to accept both on the
  // same cycle. '0 (unset, the default) for every other item — identical
  // to plain drive_write() dispatch, no other scenario's driving changes.
  bit                     fallthrough_probe;

  `uvm_object_utils_begin(axi_seq_item)
    `uvm_field_int(is_write, UVM_ALL_ON)
    `uvm_field_int(addr,     UVM_ALL_ON)
    `uvm_field_int(len,      UVM_ALL_ON)
    `uvm_field_int(id,       UVM_ALL_ON)
  `uvm_object_utils_end

  function new(string name = "axi_seq_item");
    super.new(name);
    size  = xbar_types_pkg::BEAT_SIZE;
    burst = axi_pkg::BURST_INCR;
    atop  = '0;
  endfunction
endclass

// M2-OR01/OR02 same-ID cross-port ordering constructive primitive
// (uvm_env.md C5.2). Carries a *second* sub-transaction alongside the base
// axi_seq_item fields (which serve as sub-transaction "A"); the driver
// (slvport_agent.sv drive_pair()) presents B's own AW/AR immediately after
// (an optional gap past) A's own AW/AR handshake accepted, never waiting
// for A's B/R first — the only way to observe whether the DUT defers
// acceptance of a same-ID-bucket request (spec §5.2.1) or accepts it
// promptly (§5.2.4/differing direction).
class axi_pair_item extends axi_seq_item;
  axi_seq_item  second_item;
  int unsigned  gap_cycles;

  `uvm_object_utils(axi_pair_item)

  function new(string name = "axi_pair_item");
    super.new(name);
  endfunction
endclass

// M2-TL01/TL02 sustained-pressure primitive (uvm_env.md C5.3). Carries an
// ordered list of same-direction sub-transactions the driver presents
// back-to-back WITHOUT waiting for each one's B/R first (slvport_agent.sv
// drive_burst()): the only way to build the per-(bucket|id) in-flight count
// up to the DUT's transaction-number ceiling (spec §5.4). Every sub-item is
// the same direction so a single completion counter (B for writes, R-last
// for reads) tallies the burst; all sub-items live on one slave port and one
// burst runs to completion before the next (the sequence serialises them),
// so no other traffic aliases the count.
class axi_burst_item extends axi_seq_item;
  axi_seq_item items[$];

  // M4-EB01 response-side backpressure selector (testplan M4-EB01, spec
  // §4.3/§7.4.5): when set on a WRITE burst, the driver (slvport_agent.sv
  // drive_burst) holds this slave port's b_ready LOW for a bounded window and
  // presents the burst's AWs decoupled from (ahead of) their W bursts, so the
  // port's internal err_slv fills its B-response fifo and then its w_fifo,
  // driving its input-side w_ready/aw_ready low (the structural coverage
  // motive). '0 (default) for every other axi_burst_item (M2-TL01/TL02/
  // M3-TL01/M3-OR05), whose b_ready stays tied high and whose AW/W stay
  // presented sequentially exactly as before. Pure stimulus timing on the
  // response side — never changes any payload/id/completion order (a master
  // may delay b_ready arbitrarily, legal AXI4, spec §1).
  bit b_backpressure;

  `uvm_object_utils(axi_burst_item)

  function new(string name = "axi_burst_item");
    super.new(name);
  endfunction
endclass

// "input observation" (slvport_monitor) / "output observation" request-side
// record (mstport_monitor), keyed by the observing port's own `port_idx`
// and, for matching in the scoreboard, by `id` (mst-side id space, spec
// §5.1.4 — disjoint per source slv port, so id alone is a safe match key).
class axi_req_obs extends uvm_object;
  int unsigned            port_idx;
  bit                     is_write;
  bit [xbar_types_pkg::ID_W_MST-1:0] id; // zero-extended on the slv side
  xbar_types_pkg::addr_t  addr;
  axi_pkg::len_t          len;
  axi_pkg::size_t         size;
  axi_pkg::burst_t        burst;
  xbar_types_pkg::data_t  wdata[$]; // populated for writes only
  xbar_types_pkg::strb_t  wstrb[$];
  // aw.atop as observed at the AW handshake ('0 for reads and ordinary
  // writes) — lets the scoreboard register the M2-AT01 B+R pair expectation
  // (spec §6.3) and check atop pass-through to the master port (spec §1/§6.1).
  axi_pkg::atop_t         atop;
  // AW/AR handshake (valid&&ready) instant — reusable accept-timestamp
  // infrastructure (scoreboard_refmodel.md C5.5(a)); populated by the
  // monitor at the actual handshake cycle (writes: captured at AW accept,
  // carried through to the req_obs built at the burst's w_last; reads: the
  // req_obs itself is already built at the AR accept instant).
  time                    accept_time;

  `uvm_object_utils(axi_req_obs)
  function new(string name = "axi_req_obs");
    super.new(name);
    atop = '0;
  endfunction
endclass

// Full round-trip record captured purely at the slv port (request + its own
// response) — used for response-payload / resp-code judgement
// (scoreboard_refmodel.md §4, C4.2).
class axi_resp_obs extends uvm_object;
  int unsigned            port_idx; // slv port index
  bit                     is_write;
  xbar_types_pkg::id_slv_t id;
  xbar_types_pkg::addr_t  addr;
  axi_pkg::len_t          len;
  axi_pkg::size_t         size;
  axi_pkg::burst_t        burst;
  xbar_types_pkg::data_t  rdata[$];  // read only
  axi_pkg::resp_t         resp[$];   // per-beat (read) or single-entry (write B)
  // B or R-last handshake instant — reusable completion-timestamp
  // infrastructure (scoreboard_refmodel.md C5.5(a)); both are already built
  // exactly at their completion instant, so this is a plain `$time` stamp.
  time                    complete_time;

  `uvm_object_utils(axi_resp_obs)
  function new(string name = "axi_resp_obs");
    super.new(name);
  endfunction
endclass
