// tb/axi_txn.sv — M1 UVM env transaction items. `include-d from tb_pkg.sv
// (package xbar_tb_pkg), after xbar_types_pkg/axi_if are compiled.
//
// axi_seq_item: stimulus generated by a slvport sequence and driven onto a
// crossbar slave port (write or read burst request). AW/AR fields only —
// data/strb for writes are supplied inline.
//
// axi_obs_item: what a monitor observed on the bus (request- or full
// round-trip-side), fed to the scoreboard's analysis imps. One class serves
// both "input observation" (slv side, spec §5.1 source index) and "output
// observation" (mst side) roles per scoreboard_refmodel.md §0; `port_idx`
// carries whichever port the observing monitor is attached to.

class axi_seq_item extends uvm_sequence_item;
  rand bit               is_write;
  rand xbar_types_pkg::addr_t addr;
  rand axi_pkg::len_t     len;   // AxLEN (beats - 1)
  axi_pkg::size_t         size; // fixed full-width beats (BEAT_SIZE)
  axi_pkg::burst_t        burst; // fixed INCR
  rand xbar_types_pkg::id_slv_t id;
  xbar_types_pkg::data_t  wdata[$];
  xbar_types_pkg::strb_t  wstrb[$];

  `uvm_object_utils_begin(axi_seq_item)
    `uvm_field_int(is_write, UVM_ALL_ON)
    `uvm_field_int(addr,     UVM_ALL_ON)
    `uvm_field_int(len,      UVM_ALL_ON)
    `uvm_field_int(id,       UVM_ALL_ON)
  `uvm_object_utils_end

  function new(string name = "axi_seq_item");
    super.new(name);
    size  = xbar_types_pkg::BEAT_SIZE;
    burst = axi_pkg::BURST_INCR;
  endfunction
endclass

// "input observation" (slvport_monitor) / "output observation" request-side
// record (mstport_monitor), keyed by the observing port's own `port_idx`
// and, for matching in the scoreboard, by `id` (mst-side id space, spec
// §5.1.4 — disjoint per source slv port, so id alone is a safe match key).
class axi_req_obs extends uvm_object;
  int unsigned            port_idx;
  bit                     is_write;
  bit [xbar_types_pkg::ID_W_MST-1:0] id; // zero-extended on the slv side
  xbar_types_pkg::addr_t  addr;
  axi_pkg::len_t          len;
  axi_pkg::size_t         size;
  axi_pkg::burst_t        burst;
  xbar_types_pkg::data_t  wdata[$]; // populated for writes only
  xbar_types_pkg::strb_t  wstrb[$];

  `uvm_object_utils(axi_req_obs)
  function new(string name = "axi_req_obs");
    super.new(name);
  endfunction
endclass

// Full round-trip record captured purely at the slv port (request + its own
// response) — used for response-payload / resp-code judgement
// (scoreboard_refmodel.md §4, C4.2).
class axi_resp_obs extends uvm_object;
  int unsigned            port_idx; // slv port index
  bit                     is_write;
  xbar_types_pkg::id_slv_t id;
  xbar_types_pkg::addr_t  addr;
  axi_pkg::len_t          len;
  axi_pkg::size_t         size;
  axi_pkg::burst_t        burst;
  xbar_types_pkg::data_t  rdata[$];  // read only
  axi_pkg::resp_t         resp[$];   // per-beat (read) or single-entry (write B)

  `uvm_object_utils(axi_resp_obs)
  function new(string name = "axi_resp_obs");
    super.new(name);
  endfunction
endclass
