// tb/mstport_agent.sv — M1 UVM env: agent attached to one crossbar *master*
// port (TB plays the external AXI slave, uvm_env.md §3 "slave agent").
// `include-d from tb_pkg.sv.
//
// mstport_responder: reactive AXI4 slave. Accepts AW/AR whenever presented
// (no artificial backpressure), queues them, and processes writes/reads to
// completion via two independent, FIFO-ordered response loops — a write
// burst is answered with a single B once its whole W burst has been
// collected (spec §1 AXI4 baseline), a read burst is answered with
// AxLEN+1 R beats generated by the shared, address-only, deterministic
// xbar_types_pkg::predict_beat_data() function (uvm_env.md C3.1). ATOP dual
// (B+R) response tracking (spec §6.3, scoreboard_refmodel.md C6.3) is left
// as a documented TODO: M1-01 issues no ATOP transactions
// (uvm_env.md C2.4 note), so it is out of this card's exercised scope; M2
// activates it alongside the rest of the ATOP judgement path.
//
// mstport_monitor: purely passive (Monitor modport) request-side observer
// ("output observation", scoreboard_refmodel.md §0); response-payload
// correctness is judged entirely from the slv-side round trip
// (slvport_monitor), so this monitor does not need to watch B/R.

class mstport_responder extends uvm_component;
  `uvm_component_utils(mstport_responder)

  virtual mstport_if vif;
  int unsigned         port_idx;

  typedef struct {
    xbar_types_pkg::id_mst_t id;
    xbar_types_pkg::addr_t   addr;
    axi_pkg::len_t           len;
    axi_pkg::size_t          size;
    axi_pkg::burst_t         burst;
  } req_rec_t;

  local req_rec_t aw_pending_q[$];
  local req_rec_t ar_pending_q[$];
  local req_rec_t write_todo_q[$];

  function new(string name, uvm_component parent);
    super.new(name, parent);
  endfunction

  virtual function void build_phase(uvm_phase phase);
    super.build_phase(phase);
    if (!uvm_config_db#(virtual mstport_if)::get(this, "", "vif", vif))
      `uvm_fatal("NOVIF", "mstport_responder: virtual interface not set")
    if (!uvm_config_db#(int)::get(this, "", "port_idx", port_idx))
      `uvm_fatal("NOPIDX", "mstport_responder: port_idx not set")
  endfunction

  task automatic drive_idle();
    vif.aw_ready <= 1'b0;
    vif.ar_ready <= 1'b0;
    vif.w_ready  <= 1'b0;
    vif.b_valid  <= 1'b0;
    vif.r_valid  <= 1'b0;
  endtask

  virtual task run_phase(uvm_phase phase);
    drive_idle();
    wait (vif.rst_ni === 1'b1);
    fork
      accept_loop();
      w_collect_loop();
      b_respond_loop();
      r_respond_loop();
    join
  endtask

  task automatic accept_loop();
    vif.aw_ready <= 1'b1;
    vif.ar_ready <= 1'b1;
    forever begin
      @(posedge vif.clk_i);
      if (vif.aw_valid && vif.aw_ready) begin
        req_rec_t r;
        r.id = vif.aw_id; r.addr = vif.aw_addr; r.len = vif.aw_len;
        r.size = vif.aw_size; r.burst = vif.aw_burst;
        aw_pending_q.push_back(r);
      end
      if (vif.ar_valid && vif.ar_ready) begin
        req_rec_t r;
        r.id = vif.ar_id; r.addr = vif.ar_addr; r.len = vif.ar_len;
        r.size = vif.ar_size; r.burst = vif.ar_burst;
        ar_pending_q.push_back(r);
      end
    end
  endtask

  // Collects one full W burst per accepted AW, FIFO-paired (spec §5.5.1: W
  // burst maintains its AW's order and is not interleaved with another
  // source's beats — a property this env's own drivers uphold).
  task automatic w_collect_loop();
    bit       w_busy;
    req_rec_t cur;
    w_busy = 1'b0;
    vif.w_ready <= 1'b1;
    forever begin
      @(posedge vif.clk_i);
      if (vif.w_valid && vif.w_ready) begin
        if (!w_busy) begin
          if (aw_pending_q.size() > 0) cur = aw_pending_q.pop_front();
          w_busy = 1'b1;
        end
        if (vif.w_last) begin
          write_todo_q.push_back(cur);
          w_busy = 1'b0;
        end
      end
    end
  endtask

  task automatic b_respond_loop();
    forever begin
      req_rec_t cur;
      wait (write_todo_q.size() > 0);
      cur = write_todo_q.pop_front();
      vif.b_id    <= cur.id;
      vif.b_resp  <= axi_pkg::RESP_OKAY;
      vif.b_user  <= '0;
      vif.b_valid <= 1'b1;
      do @(posedge vif.clk_i); while (!vif.b_ready);
      vif.b_valid <= 1'b0;
    end
  endtask

  task automatic r_respond_loop();
    forever begin
      req_rec_t cur;
      wait (ar_pending_q.size() > 0);
      cur = ar_pending_q.pop_front();
      for (int unsigned k = 0; k <= cur.len; k++) begin
        xbar_types_pkg::data_t beat_data;
        beat_data = xbar_types_pkg::predict_beat_data(cur.addr, cur.size,
                                                        cur.len, cur.burst, k);
        vif.r_id    <= cur.id;
        vif.r_data  <= beat_data;
        vif.r_resp  <= axi_pkg::RESP_OKAY;
        vif.r_last  <= (k == cur.len);
        vif.r_user  <= '0;
        vif.r_valid <= 1'b1;
        do @(posedge vif.clk_i); while (!vif.r_ready);
      end
      vif.r_valid <= 1'b0;
    end
  endtask
endclass

class mstport_monitor extends uvm_monitor;
  `uvm_component_utils(mstport_monitor)

  virtual mstport_if vif;
  int unsigned         port_idx;
  uvm_analysis_port #(axi_req_obs) req_ap;

  local bit                      w_busy;
  local xbar_types_pkg::id_mst_t w_id;
  local xbar_types_pkg::addr_t   w_addr;
  local axi_pkg::len_t           w_len;
  local axi_pkg::size_t          w_size;
  local axi_pkg::burst_t         w_burst;
  local xbar_types_pkg::data_t   w_data_q[$];
  local xbar_types_pkg::strb_t   w_strb_q[$];

  function new(string name, uvm_component parent);
    super.new(name, parent);
    req_ap = new("req_ap", this);
  endfunction

  virtual function void build_phase(uvm_phase phase);
    super.build_phase(phase);
    if (!uvm_config_db#(virtual mstport_if)::get(this, "", "vif", vif))
      `uvm_fatal("NOVIF", "mstport_monitor: virtual interface not set")
    if (!uvm_config_db#(int)::get(this, "", "port_idx", port_idx))
      `uvm_fatal("NOPIDX", "mstport_monitor: port_idx not set")
  endfunction

  virtual task run_phase(uvm_phase phase);
    w_busy = 1'b0;
    forever begin
      @(posedge vif.clk_i);
      if (!vif.rst_ni) continue;

      if (vif.aw_valid && vif.aw_ready) begin
        w_id    = vif.aw_id;
        w_addr  = vif.aw_addr;
        w_len   = vif.aw_len;
        w_size  = vif.aw_size;
        w_burst = vif.aw_burst;
        w_data_q.delete();
        w_strb_q.delete();
        w_busy = 1'b1;
      end
      if (w_busy && vif.w_valid && vif.w_ready) begin
        w_data_q.push_back(vif.w_data);
        w_strb_q.push_back(vif.w_strb);
        if (vif.w_last) begin
          axi_req_obs ro = axi_req_obs::type_id::create("mst_wreq_obs");
          ro.port_idx = port_idx;
          ro.is_write = 1'b1;
          ro.id       = w_id;
          ro.addr     = w_addr;
          ro.len      = w_len;
          ro.size     = w_size;
          ro.burst    = w_burst;
          ro.wdata    = w_data_q;
          ro.wstrb    = w_strb_q;
          req_ap.write(ro);
          w_busy = 1'b0;
        end
      end

      if (vif.ar_valid && vif.ar_ready) begin
        axi_req_obs ro = axi_req_obs::type_id::create("mst_rreq_obs");
        ro.port_idx = port_idx;
        ro.is_write = 1'b0;
        ro.id       = vif.ar_id;
        ro.addr     = vif.ar_addr;
        ro.len      = vif.ar_len;
        ro.size     = vif.ar_size;
        ro.burst    = vif.ar_burst;
        req_ap.write(ro);
      end
    end
  endtask
endclass

class mstport_agent extends uvm_agent;
  `uvm_component_utils(mstport_agent)

  mstport_responder responder;
  mstport_monitor    monitor;

  function new(string name, uvm_component parent);
    super.new(name, parent);
  endfunction

  virtual function void build_phase(uvm_phase phase);
    super.build_phase(phase);
    responder = mstport_responder::type_id::create("responder", this);
    monitor   = mstport_monitor::type_id::create("monitor", this);
  endfunction
endclass
