// tb/mstport_agent.sv — M1 UVM env: agent attached to one crossbar *master*
// port (TB plays the external AXI slave, uvm_env.md §3 "slave agent").
// `include-d from tb_pkg.sv.
//
// mstport_responder: reactive AXI4 slave. Accepts AW/AR whenever presented
// (no artificial backpressure), queues them, and processes writes/reads to
// completion via two independent, FIFO-ordered response loops — a write
// burst is answered with a single B once its whole W burst has been
// collected (spec §1 AXI4 baseline), a read burst is answered with
// AxLEN+1 R beats generated by the shared, address-only, deterministic
// xbar_types_pkg::predict_beat_data() function (uvm_env.md C3.1). ATOP dual
// (B+R) response (spec §6.3, uvm_env.md C3.4, M2-AT01): an AW whose
// aw.atop[ATOP_R_RESP] is set (atomic load) is additionally queued for the
// read-response loop once its W burst is collected, so the responder
// returns *both* a B and an R burst (same ID, AxLEN+1 beats of
// predict_beat_data — the deterministic "old value" the scoreboard can
// predict). B-vs-R emission order is left to the two independent response
// loops (delay-insensitive, spec §7.4 — no order is asserted anywhere).
//
// mstport_monitor: purely passive (Monitor modport) request-side observer
// ("output observation", scoreboard_refmodel.md §0); response-payload
// correctness is judged entirely from the slv-side round trip
// (slvport_monitor), so this monitor does not need to watch B/R.

class mstport_responder extends uvm_component;
  `uvm_component_utils(mstport_responder)

  virtual mstport_if vif;
  int unsigned         port_idx;

  // Bounded, protocol-legal response delay (uvm_env.md C5.3): held cycles the
  // responder waits before driving each B / R response. Default 0 — every M1
  // and other-M2 test keeps the reactive responder exactly as before. The
  // M2-TL01/TL02 sustained-pressure tests set it >0 (config_db) so responses
  // drain slowly enough that the per-(bucket|id) in-flight count is genuinely
  // pushed up to the DUT's ceiling (spec §5.4) instead of the responder
  // draining so fast the limit is never reached ("空转" avoidance). This is a
  // legal AXI slave that simply asserts b_valid/r_valid a few cycles later; no
  // ordering or payload changes.
  int unsigned resp_hold = 0;

  // M4-AW01 (testplan M4-AW01, spec §7.4 items 1/5 — backpressure is a
  // legal, delay-insensitive slave stimulus): optional, off-by-default
  // periodic backpressure on `aw_ready` ONLY (`ar_ready` untouched). Default
  // 0 keeps every other test's `aw_ready` tie-high exactly as before (byte-
  // identical to the pre-existing single `vif.aw_ready <= 1'b1;`); the
  // M4-AW01 test config_db-sets this true on ONE master port's responder
  // before build_phase, so >=2 concurrent source AW requests at that port
  // hit a genuinely not-ready cycle and force the DUT's arbiter to retry
  // its selection (structural motive only — see accept_loop()). The
  // hold/high period (BP_HOLD_CYC) is a simplification: this env does not
  // (and per CLAUDE.md's input boundary must not) know which cycle the
  // DUT's arbiter actually decided on, so it just denies periodically.
  bit                    bp_enable = 1'b0;
  local int unsigned     bp_cnt;
  localparam int unsigned BP_HOLD_CYC = 2; // aw_ready low this many cycles, then 1 cycle high

  typedef struct {
    xbar_types_pkg::id_mst_t id;
    xbar_types_pkg::addr_t   addr;
    axi_pkg::len_t           len;
    axi_pkg::size_t          size;
    axi_pkg::burst_t         burst;
    axi_pkg::atop_t          atop; // spec §6.1 — '0 for AR-side records
  } req_rec_t;

  local req_rec_t aw_pending_q[$];
  local req_rec_t ar_pending_q[$];
  local req_rec_t write_todo_q[$];

  // BUG-0042 (M4-FT01, TB_BUG — see mstport_monitor's class-header note
  // above for the full RCA): under cfgE (`FallThrough=1'b1`) a W burst can
  // finish at this master port before its own AW has been accepted here
  // (`CUT_ALL_AX`'s `MuxAw` spill register delays AW, `MuxW` has none).
  // `w_cur`/`w_cur_has_aw` move from w_collect_loop()-local to class-level
  // so accept_loop() can retroactively resolve a still-collecting burst;
  // `orphan_pending_cnt` counts ALREADY-FINISHED W bursts whose AW has not
  // arrived yet (FIFO — the next AW to arrive always resolves the oldest
  // one). Before this fix, an AW-less w_last silently reused whatever
  // stale `cur` a task-local var happened to hold (id 0 on this port's
  // very first-ever write) and queued a B with the WRONG id — the
  // driver's `wait (vif.b_id == item.id)` then hung forever waiting for a
  // B that was already sent under the wrong id, which is what surfaced as
  // the tb_top watchdog timeout, not a UVM_ERROR.
  local req_rec_t     w_cur;
  local bit           w_cur_has_aw;
  local int unsigned  orphan_pending_cnt;

  function new(string name, uvm_component parent);
    super.new(name, parent);
  endfunction

  virtual function void build_phase(uvm_phase phase);
    super.build_phase(phase);
    if (!uvm_config_db#(virtual mstport_if)::get(this, "", "vif", vif))
      `uvm_fatal("NOVIF", "mstport_responder: virtual interface not set")
    if (!uvm_config_db#(int)::get(this, "", "port_idx", port_idx))
      `uvm_fatal("NOPIDX", "mstport_responder: port_idx not set")
    // Optional: absent config keeps the default 0 (immediate response).
    void'(uvm_config_db#(int)::get(this, "", "resp_hold", resp_hold));
    // Optional: absent config keeps the default 0 (no backpressure, M4-AW01).
    void'(uvm_config_db#(bit)::get(this, "", "bp_enable", bp_enable));
  endfunction

  task automatic drive_idle();
    vif.aw_ready <= 1'b0;
    vif.ar_ready <= 1'b0;
    vif.w_ready  <= 1'b0;
    vif.b_valid  <= 1'b0;
    vif.r_valid  <= 1'b0;
  endtask

  virtual task run_phase(uvm_phase phase);
    drive_idle();
    wait (vif.rst_ni === 1'b1);
    w_cur_has_aw       = 1'b0;
    orphan_pending_cnt = 0;
    fork
      accept_loop();
      w_collect_loop();
      b_respond_loop();
      r_respond_loop();
    join
  endtask

  // BUG-0042: pushes an already-resolved write straight to write_todo_q
  // (+ ar_pending_q for an atomic load) — shared by the normal AW-then-W
  // path (w_collect_loop) and an AW arriving late to resolve an
  // already-finished orphan (accept_loop).
  task automatic queue_write_done(req_rec_t r);
    write_todo_q.push_back(r);
    // Atomic load (spec §6.3, uvm_env.md C3.4): the same request also owes
    // an R burst — hand it to the read-response loop (shared queue keeps
    // the R channel single-driver).
    if (r.atop[axi_pkg::ATOP_R_RESP])
      ar_pending_q.push_back(r);
  endtask

  task automatic accept_loop();
    bp_cnt = 0;
    vif.aw_ready <= bp_enable ? 1'b0 : 1'b1;
    vif.ar_ready <= 1'b1;
    forever begin
      @(posedge vif.clk_i);
      // M4-AW01: when enabled, periodically deny aw_ready regardless of
      // whether anything is currently requesting it — a legal, delay-
      // insensitive backpressure pattern (spec §7.4 items 1/5) that does not
      // need to know which cycle the DUT's arbiter picked (see bp_enable
      // header comment above). Every other test (bp_enable=0) skips this
      // block entirely, so aw_ready stays tied high exactly as before.
      if (bp_enable) begin
        vif.aw_ready <= (bp_cnt == BP_HOLD_CYC) ? 1'b1 : 1'b0;
        bp_cnt = (bp_cnt == BP_HOLD_CYC) ? 0 : bp_cnt + 1;
      end
      if (vif.aw_valid && vif.aw_ready) begin
        req_rec_t r;
        r.id = vif.aw_id; r.addr = vif.aw_addr; r.len = vif.aw_len;
        r.size = vif.aw_size; r.burst = vif.aw_burst;
        r.atop = vif.aw_atop;
        // BUG-0042: resolve the OLDEST unresolved write first — an
        // already-finished orphan (FIFO priority, spec §5.5.1/§5.5.2),
        // else the burst currently being collected (if it has no AW yet),
        // else this is a normal AW-ahead-of-its-W arrival.
        if (orphan_pending_cnt > 0) begin
          orphan_pending_cnt--;
          queue_write_done(r);
        end else if (w_cur_has_aw == 1'b0 && w_busy_get()) begin
          w_cur        = r;
          w_cur_has_aw = 1'b1;
        end else begin
          aw_pending_q.push_back(r);
        end
      end
      if (vif.ar_valid && vif.ar_ready) begin
        req_rec_t r;
        r.id = vif.ar_id; r.addr = vif.ar_addr; r.len = vif.ar_len;
        r.size = vif.ar_size; r.burst = vif.ar_burst;
        r.atop = '0;
        ar_pending_q.push_back(r);
      end
    end
  endtask

  // BUG-0042: w_busy itself stays w_collect_loop-local (only that task
  // drives it); accept_loop only needs to know "is a burst mid-collection
  // right now" to decide whether an AW-less w_cur is waiting to be filled
  // in. Exposed via this tiny accessor instead of promoting w_busy to a
  // class field with two writers.
  local bit w_busy_shadow;
  function automatic bit w_busy_get(); return w_busy_shadow; endfunction

  // Collects one full W burst per accepted AW, FIFO-paired (spec §5.5.1: W
  // burst maintains its AW's order and is not interleaved with another
  // source's beats — a property this env's own drivers uphold). BUG-0042:
  // an empty aw_pending_q at burst-start no longer stalls anything — the
  // burst simply collects "AW pending" (w_cur_has_aw=0) and gets resolved
  // retroactively by accept_loop() above, or parked in orphan_pending_cnt
  // at w_last if the AW still hasn't shown up.
  task automatic w_collect_loop();
    w_busy_shadow = 1'b0;
    vif.w_ready <= 1'b1;
    forever begin
      @(posedge vif.clk_i);
      if (vif.w_valid && vif.w_ready) begin
        if (!w_busy_shadow) begin
          if (aw_pending_q.size() > 0) begin
            w_cur        = aw_pending_q.pop_front();
            w_cur_has_aw = 1'b1;
          end else begin
            w_cur_has_aw = 1'b0;
          end
          w_busy_shadow = 1'b1;
        end
        if (vif.w_last) begin
          if (w_cur_has_aw) queue_write_done(w_cur);
          else orphan_pending_cnt++;
          w_busy_shadow = 1'b0;
        end
      end
    end
  endtask

  task automatic b_respond_loop();
    forever begin
      req_rec_t cur;
      wait (write_todo_q.size() > 0);
      cur = write_todo_q.pop_front();
      repeat (resp_hold) @(posedge vif.clk_i); // uvm_env.md C5.3 bounded hold
      vif.b_id    <= cur.id;
      vif.b_resp  <= axi_pkg::RESP_OKAY;
      vif.b_user  <= '0;
      vif.b_valid <= 1'b1;
      do @(posedge vif.clk_i); while (!vif.b_ready);
      vif.b_valid <= 1'b0;
    end
  endtask

  task automatic r_respond_loop();
    forever begin
      req_rec_t cur;
      wait (ar_pending_q.size() > 0);
      cur = ar_pending_q.pop_front();
      repeat (resp_hold) @(posedge vif.clk_i); // uvm_env.md C5.3 bounded hold
      for (int unsigned k = 0; k <= cur.len; k++) begin
        xbar_types_pkg::data_t beat_data;
        beat_data = xbar_types_pkg::predict_beat_data(cur.addr, cur.size,
                                                        cur.len, cur.burst, k);
        vif.r_id    <= cur.id;
        vif.r_data  <= beat_data;
        vif.r_resp  <= axi_pkg::RESP_OKAY;
        vif.r_last  <= (k == cur.len);
        vif.r_user  <= '0;
        vif.r_valid <= 1'b1;
        do @(posedge vif.clk_i); while (!vif.r_ready);
      end
      vif.r_valid <= 1'b0;
    end
  endtask
endclass

class mstport_monitor extends uvm_monitor;
  `uvm_component_utils(mstport_monitor)

  virtual mstport_if vif;
  int unsigned         port_idx;
  uvm_analysis_port #(axi_req_obs) req_ap;

  // AW→W burst pairing. At a master port the mux may accept an AW ahead of
  // (or decoupled from) its W burst, and write bursts from several slave
  // ports converge here; W bursts stay non-interleaved and in AW-acceptance
  // order (spec §5.5.2), so a FIFO of accepted AWs — popped as each W burst
  // starts and completed at its w_last — pairs them correctly. (An earlier
  // single-slot "capture AW / collect until w_last" scheme mis-paired beats
  // whenever a second AW was accepted before the first burst's W finished,
  // BUG-0009.)
  //
  // BUG-0042 (M4-FT01, TB_BUG): the FIFO above assumed an AW is always
  // accepted no later than its own W burst's first beat. AXI4 does not
  // guarantee that relative order — the AW and W channels are independent
  // (spec §5.5 has no clause requiring it; it only constrains W-burst-vs-
  // W-burst order via AW acceptance order, §5.5.1/§5.5.2). Under cfgE
  // (`FallThrough=1'b1`) combined with the baseline `LatencyMode=
  // CUT_ALL_AX` (`MuxAw` spill register present, `MuxW` absent — spec
  // §7.2), a write's W burst can reach this master port and complete
  // BEFORE its own AW clears the `MuxAw` spill — a live, reproducible
  // reordering (`make run TEST=m4_ft01_cfge_test SEED=1` before this fix,
  // confirmed via a temporary per-cycle valid/ready trace showing
  // `w_valid&&w_ready` at mst port 5 with `aw_valid==0` one full cycle
  // before that same write's AW appears). `orphan_w_q` below buffers a
  // COMPLETED W burst that had no AW queued at its start, so an AW arriving
  // afterward — for the currently-collecting burst (`w_cur_has_aw`) or a
  // fully-finished one (`orphan_w_q`) — still gets paired and published
  // correctly instead of raising the false MON_WNOAW error and orphaning
  // every later pairing. No published record's content changes (same
  // id/addr/len/wdata/wstrb/atop fields, same axi_req_obs shape) — only
  // WHEN the publish happens, and the publish code is now the shared
  // do_publish() task instead of duplicated inline.
  typedef struct {
    xbar_types_pkg::id_mst_t id;
    xbar_types_pkg::addr_t   addr;
    axi_pkg::len_t           len;
    axi_pkg::size_t          size;
    axi_pkg::burst_t         burst;
    axi_pkg::atop_t          atop; // spec §6.1 — pass-through check input
  } aw_rec_t;

  typedef struct {
    xbar_types_pkg::data_t wdata[$];
    xbar_types_pkg::strb_t wstrb[$];
  } orphan_w_rec_t;

  local aw_rec_t                 aw_q[$];
  local bit                      w_busy;
  local bit                      w_cur_has_aw; // BUG-0042: is w_cur resolved yet?
  local aw_rec_t                 w_cur;
  local xbar_types_pkg::data_t   w_data_q[$];
  local xbar_types_pkg::strb_t   w_strb_q[$];
  local orphan_w_rec_t           orphan_w_q[$]; // BUG-0042: completed W bursts awaiting their AW
  local bit                      aw_was_held; // M4-AW01: aw_valid seen with aw_ready low on a prior edge

  function new(string name, uvm_component parent);
    super.new(name, parent);
    req_ap = new("req_ap", this);
  endfunction

  virtual function void build_phase(uvm_phase phase);
    super.build_phase(phase);
    if (!uvm_config_db#(virtual mstport_if)::get(this, "", "vif", vif))
      `uvm_fatal("NOVIF", "mstport_monitor: virtual interface not set")
    if (!uvm_config_db#(int)::get(this, "", "port_idx", port_idx))
      `uvm_fatal("NOPIDX", "mstport_monitor: port_idx not set")
  endfunction

  // Publishes one completed write's axi_req_obs from an already-resolved
  // aw_rec_t + its collected wdata/wstrb (BUG-0042: shared by the two
  // publish sites — normal AW-first completion, and AW arriving late to
  // resolve an already-finished orphan_w_q entry).
  task automatic do_publish(aw_rec_t a, xbar_types_pkg::data_t wdata[$],
                            xbar_types_pkg::strb_t wstrb[$]);
    axi_req_obs ro = axi_req_obs::type_id::create("mst_wreq_obs");
    ro.port_idx = port_idx;
    ro.is_write = 1'b1;
    ro.id       = a.id;
    ro.addr     = a.addr;
    ro.len      = a.len;
    ro.size     = a.size;
    ro.burst    = a.burst;
    ro.wdata    = wdata;
    ro.wstrb    = wstrb;
    ro.atop     = a.atop;
    req_ap.write(ro);
  endtask

  virtual task run_phase(uvm_phase phase);
    w_busy       = 1'b0;
    w_cur_has_aw = 1'b0;
    aw_was_held  = 1'b0;
    aw_q.delete();
    orphan_w_q.delete();
    forever begin
      @(posedge vif.clk_i);
      if (!vif.rst_ni) continue;

      // M4-AW01 non-decisional retry witness (testplan M4-AW01, spec §7.4
      // items 1/5): this AW was offered but not ready-accepted on THIS
      // edge — remember it so a later edge where it IS accepted can be
      // recognized as "held, then accepted" (AXI requires valid/payload to
      // stay stable across the hold, so no re-decode of identity is
      // needed). Purely external valid/ready observation, no DUT-internal
      // signal (cg_aw_retry header, functional_coverage.sv). Never feeds a
      // judgement — SPEC-5.5.4/7.4.3 red line.
      if (vif.aw_valid && !vif.aw_ready) aw_was_held = 1'b1;

      if (vif.aw_valid && vif.aw_ready) begin
        aw_rec_t a;
        if (aw_was_held && xbar_functional_coverage::m_probe != null)
          xbar_functional_coverage::m_probe.sample_aw_retry(1'b1);
        aw_was_held = 1'b0;
        a.id = vif.aw_id; a.addr = vif.aw_addr; a.len = vif.aw_len;
        a.size = vif.aw_size; a.burst = vif.aw_burst;
        a.atop = vif.aw_atop;
        // BUG-0042: this AW may be resolving a write whose W burst already
        // started (or even finished) before this AW showed up here — check
        // the oldest unresolved W record FIRST (FIFO order, spec §5.5.1/
        // §5.5.2: W-burst order follows AW-acceptance order), falling back
        // to the ordinary "AW arrived ahead of its W" queue.
        if (orphan_w_q.size() > 0) begin
          orphan_w_rec_t o;
          o = orphan_w_q.pop_front();
          do_publish(a, o.wdata, o.wstrb);
        end else if (w_busy && !w_cur_has_aw) begin
          w_cur        = a;
          w_cur_has_aw = 1'b1;
        end else begin
          aw_q.push_back(a);
        end
      end
      if (vif.w_valid && vif.w_ready) begin
        if (!w_busy) begin
          // Start of a new W burst: pair with the head of the accepted-AW
          // FIFO (W bursts are in AW order, non-interleaved — spec §5.5.2).
          // BUG-0042: an empty FIFO here no longer means a real pairing
          // violation — the AW may simply not have arrived at this master
          // port yet (CUT_ALL_AX `MuxAw` spill vs. no `MuxW` spill under
          // FallThrough=1, see the class header above) — so this burst
          // starts "AW pending" instead of erroring.
          if (aw_q.size() == 0) begin
            w_cur_has_aw = 1'b0;
          end else begin
            w_cur        = aw_q.pop_front();
            w_cur_has_aw = 1'b1;
          end
          w_data_q.delete();
          w_strb_q.delete();
          w_busy = 1'b1;
        end
        w_data_q.push_back(vif.w_data);
        w_strb_q.push_back(vif.w_strb);
        if (vif.w_last) begin
          if (w_cur_has_aw) begin
            do_publish(w_cur, w_data_q, w_strb_q);
          end else begin
            // BUG-0042: burst finished with no AW seen yet — park it;
            // resolved retroactively when its AW eventually arrives above.
            orphan_w_rec_t o;
            o.wdata = w_data_q;
            o.wstrb = w_strb_q;
            orphan_w_q.push_back(o);
          end
          w_busy = 1'b0;
        end
      end

      if (vif.ar_valid && vif.ar_ready) begin
        axi_req_obs ro = axi_req_obs::type_id::create("mst_rreq_obs");
        ro.port_idx = port_idx;
        ro.is_write = 1'b0;
        ro.id       = vif.ar_id;
        ro.addr     = vif.ar_addr;
        ro.len      = vif.ar_len;
        ro.size     = vif.ar_size;
        ro.burst    = vif.ar_burst;
        req_ap.write(ro);
      end
    end
  endtask
endclass

class mstport_agent extends uvm_agent;
  `uvm_component_utils(mstport_agent)

  mstport_responder responder;
  mstport_monitor    monitor;

  function new(string name, uvm_component parent);
    super.new(name, parent);
  endfunction

  virtual function void build_phase(uvm_phase phase);
    super.build_phase(phase);
    responder = mstport_responder::type_id::create("responder", this);
    monitor   = mstport_monitor::type_id::create("monitor", this);
  endfunction
endclass
